### ISSUE TITLE
PullToRefreshLayout is always visible

### ISSUE THREAD

**Issue by DavidPacioianu** [Yalantis/Phoenix#9] opened 2015-04-13 06:24 UTC
PullToRefreshLayout should be visible only when you start dragging it down. Now it is always visible and I have to set the background of  the recyclerView to 100% opacity.

**Comment by shliama** [comment] 2015-04-13 09:06
Can you give more details? 
-Now (after last update)?
-Always visible? For me - it's not. Screenshot or video would be great.

**Comment by HamedMP** [comment] 2015-04-13 14:06
I have the same problem, tried with the setVisibility(View.INVISIBLE) but the whole listview gone invisible. 
The problem is as follow:
-When there is no item in Listview, the animation is shown, even without pulling (in fact you can't even pull it to refresh)
-When there is an item, you can see the images of the animation from the margin between the rows, if there is only one row, you can see half of the image which is so awful. 
please help us to hide them while we don't need them.
Btw, thank you for such a beautiful library. 
![1](https://cloud.githubusercontent.com/assets/3755031/7117112/20e91f30-e210-11e4-8b4e-0ffc01b86571.png)
![2](https://cloud.githubusercontent.com/assets/3755031/7117111/20e65278-e210-11e4-996a-881d5a0d71d4.png)

**Comment by shliama** [comment] 2015-04-13 14:39
@DavidPacioianu @HamedMP now it is clear :)
I've updated the "dev" branch with a fix for this issue. It would be great if you pull it and try in your projects. I've also spend some time to test it. 
If everything is ok - I'll update the maven repo too.

**Comment by HamedMP** [comment] 2015-04-13 14:42
I'll try to check it at the moment and let you know, but before that,
I just updated to version 1.1.2 and the problem solved 50%, without any interaction to listview, the animation is not shown, but when you touch it or ..., it shows again, so only when the view is created everything is ok until you touch something. 

Btw, is there a way to use DEV branch from Gradle or we should download the source and compile it on our owns?

**Comment by shliama** [comment] 2015-04-13 15:32
@HamedMP now it's only possible to include dev branch as module to your project. Sample uses it in this way too, so you can check how it's done.

**Comment by DavidPacioianu** [comment] 2015-04-13 16:51
@shliama I have tried the dev branch module and the recyclerView padding is no longer working and the only thing that happens now is to make the recyclerview opaque, which is not what I expected ( I expected that the refreshLayout will be invisible) and because of that , if set a top margin for the list item it (the margin) becomes opaque and will cover a part of the refreshLayout.
![device-2015-04-13-194945](https://cloud.githubusercontent.com/assets/10657845/7120521/6bec5438-e216-11e4-92cf-5bee3d35fd0a.png)

**Comment by shliama** [comment] 2015-04-14 10:19
@DavidPacioianu I haven't tested the library with recyclerView yet. Gonna do this asap (at the moment I don't have enough free time) and post an update here.

**Comment by alokedesai** [comment] 2015-05-07 14:29
Any update on this? I'm having the same problem. This is what it looks like for me: 
![image](https://cloud.githubusercontent.com/assets/4110292/7517593/3f45cb44-f4d6-11e4-9dba-7fb257eaf0ed.png)

**Comment by shliama** [comment] 2015-05-07 14:39
@alokedesai do you use RecyclerView? If not - try to use dev branch, this issue must be fixed there.
I haven't tested this lib with RecyclerView and at the moment I do not have time to do this.
Any pull-requests with fixes will be appreciated :)

**Comment by PGMacDesign** [comment] 2015-05-28 22:41
First off, amazing job on this project. Animation looks incredible. 

I too am using this with the RecyclerView (Specifically android.support.v7.widget.RecyclerView) and it looks exactly as alokedesai's does where the image end up taking up a section of the background. Just wanted to ping it as well as I look forward to including this in my app once that recyclerView problem gets solved.
-Pat

**Comment by shliama** [comment] 2015-05-30 13:03
@PGMacDesign @alokedesai I've just updated master branch and maven repo with version 1.2.0. 
You can check out the new sample with both ListView and RecyclerView examples.
Please leave a feedback if you have any issues with the library.

**Comment by HamedMP** [comment] 2015-05-30 15:59
Wow, Thank you very much, it's solved ^_^
(The problem with listview solved)

**Comment by PGMacDesign** [comment] 2015-06-01 18:43
Shliama, fantastic work! It is flawless with a recyclerview now. Thank you so much for your time and brilliance with this Library.

**Closed as completed** 2015-06-02 10:34 UTC
Labels: bug
